language: node_js
node_js:
    - 'node'

cache:
    directories:
        - node_modules
        # folder with Cypress binary
        - ~/.cache
addons:
    apt:
        packages:
            # needed by Cypress, not in Ubuntu 16+ by default
            - libgconf-2-4

script:
    - npm run lint
    - npm run cypress:ci
    - npm run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
        branch: master
